config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users do
    get :change_permission, on: :member
  end
  resources :sessions
  get 'users/new'

  resources :posts do
    get :favourite, on: :member
    resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'
  get 'auth/vkontakte/callback', to: 'omniauth#create'
  
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/comment.rb
#
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/favourite_post.rb
class FavouritePost < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  def self.manage(post)
    object = find_by(post: post)
    object ? object.destroy : create(post: post)
  end

end

app/models/post.rb
#
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :favourite_posts
  belongs_to :user
  has_and_belongs_to_many :categories
  validates :title, presence: true, length: { minimum: 5 }
  validates :title, presence: true
  mount_uploader :image, ImageUploader

  self.per_page = 2
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :email, :password, :password_confirmation
  mount_uploader :avatar, AvatarUploader

  attr_accessor :password
  before_create :build_default_profile
  has_one :profile
  has_many :posts, dependent: :destroy
  has_many :favourite_posts, dependent: :destroy
  has_many :account, dependent: :destroy
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  self.per_page = 8
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  private

  def build_default_profile
    build_profile
    puts 'profile has been added'
  end
end

app/controllers/application_controller.rb
#
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authorize
    redirect_to log_in_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/comments_controller.rb
#
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/omniauth_controller.rb
#
class OmniauthComtroller < ApplicationController
  def create
    binding.pry
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/pages_controller.rb
#
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
#
class PostsController < ApplicationController
  before_action :authorize, only: [:index, :new, :show, :edit, :update, :destroy]
  before_action :current_post, only: [:show, :edit, :update, :destroy, :favourite]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:categories).order(created_at: :desc).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post.increment!(:page_views)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def favourite
    current_user.favourite_posts.manage(@post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, category_ids: [])
  end

  def current_post
    @post = Post.find(params[:id])
  end

  def require_user
    redirect_to root_path unless current_user == @post.user 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_resourse, only: [:show, :edit, :update, :change_permission]

  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end
  
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def change_permission
      @user.update(admin: !@user.admin)
      redirect_to :back
    end

  private
 
    def current_resourse
      @user = User.find(params[:id])
    end

    def set_user
      @user = current_user
    end
    
    def user_params
      params.require(:user).permit(:name, :lastname, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
#
module ApplicationHelper
end

app/helpers/comments_helper.rb
#
module CommentsHelper
end

app/helpers/pages_helper.rb
#
module PagesHelper
end

app/helpers/posts_helper.rb
# Posts helper
module PostsHelper
  def require_user
  current_user == @post.user
  end

  def favourite_post(post)
    if current_user && current_user.favourite_posts.map(&:post).include?(post)
    'text-danger'
    else
    'text-muted'
    end
  end
end

app/helpers/sessions_helper.rb
#
module SessionsHelper
end

app/helpers/users_helper.rb
#
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
    <p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: { confirm: 'Are you sure'}%></p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="sidebar">
      <div id="logo", class: "img-rounded">
        <%= link_to root_path do %>
          <%= image_tag "logo.png" %>
        <% end %>
      </div>
      <ul>
        <li class="category">Website</li>
        <li><%= link_to "Blog",  root_path %></li>
        <li><%= link_to "About", about_path  %></li>
        <li><%= link_to "My Account", current_user %></li>
      </ul>
      <ul>
        <li class="category ">Social</li>
        <li>
          <%= link_to 'auth/vkontakte' do %>
            <i class="glyphicon glyphicon-xbt">Vkontakte</i>
          <% end %>
        </li>
        <li><a href = "https://www.facebook.com/pedorenko.andriu?ref=bookmarks">Facebook</a></li>
        <li><a href = "https://bitbucket.org/andreu_pedorenko1995">Bitbucket</a></li>
        <li><a href = "mailto:pedorenko.andriu@ukr.net">Email</a></li>
      </ul>
      <% if current_user.try(:admin?) %>
        <p class="sign_in"><%= link_to "Admin_Users", users_path %></p>
      <% end %>
    </div>
    <div id="main_content">
      <div id="header">
        <p>All Posts</p>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
            <% if current_user %>
              <%= image_tag current_user.avatar.url(:avat), class: "img-circle" %>
              Logged in as <%= current_user.email %>.
                <% if current_user.try(:admin?) %>
                  <p>Admin</p>
                <% else %>
                  <p>User</p>
                <% end %>
              <button class="button"><%= link_to "Log out", log_out_path %></button>
              <% else %>
              <button class="button"><%= link_to "Sign up", sign_up_path %></button> or
              <button class="button"><%= link_to "log in", log_in_path %></button>
            <% end %>
        </div>
      </div>
        <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
        <%end%>
        <%= yield %>
    </div>
  </body>
</html>


<% if current_user.try(:admin?) %>
<p><b>Admin</b></p>
<% else %>
<p><b>User</b></p>
<% end %>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "15.jpg" %>
  </div>
  <div id="content">
    <h1>Hey, I'm Pedorenko Andrey </h1>
    <p>Welcome to my blog</p>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti quibusdam laborum, quas eligendi possimus veritatis sed perferendis nobis earum fugit minus laboriosam voluptas, doloribus modi voluptates distinctio blanditiis et labore. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, minus dolor aliquam saepe, consectetur quibusdam expedita. Odio fugit recusandae reprehenderit consequatur quae, porro fuga, maxime, dolor deleniti illo adipisci velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio illo fugiat commodi, deleniti! Dolorum esse velit magni placeat voluptas, enim excepturi eligendi quasi quibusdam qui ex saepe officiis soluta, iure. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius amet minus laudantium possimus id doloremque ducimus ex voluptate eaque officia debitis architecto nemo quaerat dolorum, fuga ut esse? Similique, obcaecati.
    </p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error")%> prevented this post from saving </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><% msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
   <p>
    <%= f.label :category_ids %><br>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </p>
  <p>
  <%= f.label :image %>
  <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit post</h1>
  <%= render 'form' %>
</div>

app/views/posts/favourite.js.erb
$('#post_<%= @post.id %>').toggleClass('text-danger').toggleClass('text-muted');

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B, %D, %Y") %></p>
    <p><b>Category:</b>
    <% post.categories.each do |category| %>
      <%= category.name %>
    <% end %></p>
    <p class="image"><%= image_tag post.image.url(:thumb), class: "img-rounded" %></p>
    <% if current_user %>
      <%= link_to favourite_post_path(post), id: "post_#{post.id}", class: favourite_post(post), remote: true do %>
        <span>Like <i class = "glyphicon glyphicon-star-empty"></i></span>
      <% end %>
    <% end %>
  </div>
<% end %>
<p><center><%= will_paginate @posts %></center></p>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Новый пост</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <center><%= @post.title %></center>
  </h1>
  <div class="row">
    <div class="col-md-2">
      <p><center><%= image_tag current_user.avatar.url(:avat), class: "img-circle" %> </center></p>
      <p><center><%= @post.user.email %></center></p>
    </div>
    <div class="col-md-10">
      <p class="body">
        <p class="date">
          Submitted <%= time_ago_in_words(@post.created_at)%> Ago
          <% if require_user %>
            <%= link_to 'Edit', edit_post_path(@post),class: "label label-warning" %>
            <%= link_to 'Delete', post_path(@post),class: " label label-danger", method: :delete, data: { confirm: 'Are you sure' } %>
          <% end %> 
        </p>
        <%= @post.body %> 
        <p class = "image">
          <%= image_tag @post.image.url(:medium),  class: "img-rounded" %>
        </p>
    </div> 
  </div>
    <div class="row">
      <div class="col-md-2">

      </div>
      <div class="col-md-5">
        <p>Количество просмотров: <%=  @post.page_views %></p>
      </div>
      <div class="col-md-5">
        <p align="right">
          <i class = "glyphicon glyphicon-star-empty"></i>
          <%= @post.favourite_posts.count %>
        </p>
      </div>
    </div>
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3>Add a comment:</h3>
    <%= render 'comments/form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div id="page_wrapper">
  <center><h1>Update your profile</h1></center>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :Name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :Last_name %><br />
      <%= f.text_field :lastname %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
     <p>
      <%= f.label :avatar %>
      <%= f.file_field :avatar, class: 'my_class' %>
    </p>
    <p class="buttons"><%= f.submit %></p>
  <% end %>
</div>

app/views/users/index.html.erb
<div id="page_wrapper">
  <b><center>All Users</center></b>
  <br>
    <table class="table table-bordered">
    <tr>
      <td>№</td>
      <td>User</td>
      <td>Email</td>
      <td>Avatar</td>
      <td>Make</td>
    </tr>
    <% @users.each do |user| %>
      <div class="user_wrapper">
        <tr>
          <td><%=user.id%></td>
          <td><%=link_to user.name + " " + user.lastname, user %></td>
          <td><%=user.email%></td>
          <td><%=image_tag user.avatar.url(:avat), class: "img-circle"%></td>
          <td>
            <% if user.admin %>
            <%= link_to 'user', change_permission_user_path(user), class: "label label-primary"%>
            <% else %>
            <%= link_to 'admin', change_permission_user_path(user), class: "label label-danger" %>
            <% end %>
          </td>
        </tr>
      </div>
    <% end %>
    </table>
  <p><center><%= will_paginate @users %></center></p>
</div>

app/views/users/new.html.erb
<div id="page_wrapper">
  <center><h1>Sign Up</h1></center>
  <head>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :Name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :Last_name %><br />
      <%= f.text_field :lastname %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
     <p>
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </p>
    <p>
      <i class="fa fa-vk fa-2x"></i>
    </p>
    <p class="buttons"><%= f.submit %></p>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="page_wrapper">
<h1><center>My Account</center></h1>
<center>
  <p> 
    <%= image_tag current_user.avatar.url(:avat) %>
    <%= @user.name %>
    <%= @user.lastname %>
    </p>
    <p>
    <button type="buttonss" class="btn btn-primary"><%= link_to 'Edit_user', edit_user_path(@user) %></button>

  </p>
  </center>
</div>